# Generated by Django 3.0 on 2020-12-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('name', models.TextField(default='')),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
