# Generated by Django 3.0 on 2020-12-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201229_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Indicator_Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('Name', models.TextField(default='')),
                ('Value', models.IntegerField(default=0)),
                ('Program_IndicatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program_Indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program_Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('name', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
