# Generated by Django 3.0 on 2021-01-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_program_form_program_indicator_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_form',
            name='programId',
        ),
        migrations.RemoveField(
            model_name='program_indicator',
            name='programSdgId',
        ),
        migrations.RemoveField(
            model_name='program_indicator_target',
            name='Program_IndicatorId',
        ),
        migrations.RemoveField(
            model_name='program_sdg',
            name='programId',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Program_Form',
        ),
        migrations.DeleteModel(
            name='Program_Indicator',
        ),
        migrations.DeleteModel(
            name='Program_Indicator_Target',
        ),
        migrations.DeleteModel(
            name='Program_Sdg',
        ),
    ]
