# Generated by Django 3.0 on 2021-01-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210105_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='SdgId',
            new_name='Sdg',
        ),
    ]
