# Generated by Django 3.0 on 2021-01-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('code', models.TextField(default='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Program_Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('selectedIndicatorId', models.IntegerField(verbose_name='selected_indicator_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program_Sdg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('sdgId', models.IntegerField(verbose_name='sdg_id')),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program_Indicator_Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('Name', models.TextField(default='')),
                ('Value', models.IntegerField(default=0)),
                ('Program_IndicatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program_Indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program_indicator',
            name='programSdgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program_Sdg'),
        ),
        migrations.CreateModel(
            name='Program_Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('name', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('createdBy', models.IntegerField(default=0, verbose_name='created_by')),
                ('updatedBy', models.IntegerField(default=0, verbose_name='updated_by')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('name', models.TextField(default='')),
                ('programId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
