# Generated by Django 3.0 on 2021-01-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='programId',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='program_form',
            old_name='programId',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='program_indicator',
            old_name='programSdgId',
            new_name='programSdg',
        ),
        migrations.RenameField(
            model_name='program_indicator_target',
            old_name='Program_IndicatorId',
            new_name='Program_Indicator',
        ),
        migrations.RenameField(
            model_name='program_sdg',
            old_name='programId',
            new_name='program',
        ),
    ]
