from enum import Enum, IntEnum


class ErrorCodes(IntEnum):
    MISSING_FIELDS = 1
    GENERIC_INVALID_PARAMTERS = 2
    PROGRAM_CREATION_FAILED = 3
    PROGRAM_SDG_CREATION_FAILED = 4
    SDG_ID_NOT_SUPPLIED = 5
    SDG_CREATION_FAILED = 6
    SDG_INDICATOR_FAILED = 7

    IMAGE_UPLOAD_FAILED = 8
    IMAGE_RECORD_CREATION_FAILED = 9
    INVALID_FILE_FORMAT = 10
